version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - patch
      - dependencies
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: weekly
    labels:
      - patch
      - dependencies
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "fix"
      include: "scope"
