builds:
  - goos:
      - darwin
      - linux
      - windows
archives:
  - format: zip
brews:
  - name: aztx
    url_template: "https://github.com/riweston/aztx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: riweston
      name: homebrew-aztx
      token: "{{ .Env.HOMEBREW }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@riweston.io
    homepage: "https://github.com/riweston/aztx"
    description: "This tool is a helper for azure-cli that leverages fzf for a nice interface to switch between subscription contexts."
    license: "MIT"
    dependencies:
      - name: azure-cli
      - name: fzf
scoops:
  - name: aztx
    url_template: "https://github.com/riweston/aztx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: riweston
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@riweston.io
    homepage: "https://github.com/riweston/aztx"
    description: "This tool is a helper for azure-cli that leverages fzf for a nice interface to switch between subscription contexts."
    license: "MIT"
    depends:
      - azure-cli
      - fzf
winget:
  - name: aztx
    url_template: "https://github.com/riweston/aztx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package_identifier: "riweston.aztx"
    repository:
      owner: riweston
      name: winget-pkgs
      token: "{{ .Env.HOMEBREW }}"
      branch: "aztx-{{ .Tag }}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: main
    commit_author:
      name: Richard Weston
      email: github@riweston.io
    homepage: "https://github.com/riweston/aztx"
    short_description: "This tool is a helper for azure-cli that leverages fzf for a nice interface to switch between subscription contexts."
    license: "MIT"
    publisher: riweston
