---
name: "Continuous Deployment: Release"

on:
  workflow_run:
    workflows: ["tag"]
    branches:
      - main
    types:
      - completed

jobs:
  goreleaser:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "CD: Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW: ${{ secrets.HOMEBREW }}
