---
name: "Continuous Integration: Linting/Go Tests"

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  Lint:
    name: "CI: Linting"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: go mod tidy
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7

  Test:
    name: "CI: Go Tests"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Test
        run: |
          go mod tidy
          go test ./...
